Added variations to feed sent by bot
BoKKeR/RSS-to-Telegram-Bot pull request #43
Opened 2023-03-12 12:46 UTC by Goldac77

2023-03-12 14:08 UTC, BoKKeR requested changes
Was not able to test the functionality yet. I left some comments

2023-03-12 14:08 UTC, BoKKeR commented on src/app.update.ts
> +        let message = `No valid image\n\n<a href="${lastItem.link}">${lastItem.title}</a>`;
not used also anywhere

2023-03-12 14:08 UTC, BoKKeR commented on src/rss/rss.service.ts
> +            let rssOption_title = await this.prisma.setting.findFirst({where: {feed_type: "title"}});
you are missing where: {chat_id: fromId}, this way you just fetch the first setting of any user.

2023-03-12 14:08 UTC, BoKKeR commented on src/rss/rss.service.ts
> +                if(error.description === "Bad Request: IMAGE_PROCESS_FAILED") {
This is somewhat duplicate code from /test, you can break out the whole message creation functionality into a separate function

2023-03-12 14:08 UTC, BoKKeR commented on src/rss/rss.service.ts
> +            }
you are not using a code formatter, https://www.alphr.com/auto-format-vs-code/

2023-03-12 14:08 UTC, BoKKeR commented on src/rss/rss.service.ts
> +              gapItem.link
here you are sending a duplicate message

2023-03-12 14:08 UTC, BoKKeR commented on src/app.update.ts
> +let bot = new Telegraf(process.env.TOKEN);
you bypassed the telegramService and directly called the bot. Try using the telegramService instead to send messages. You can add functions to it

2023-03-13 20:37 UTC, Goldac77 commented on src/rss/rss.service.ts
> +            }
Just downloaded prettier code formatter, will be using it going forward

2023-03-13 20:39 UTC, Goldac77 commented on prisma/migrations/20230308110216_links_to_link/migration.sql
> +PRAGMA foreign_key_check;
The first migration was for adding feed_type to the settings model, and the second migration was for changing links to link. I thought link was better than links

2023-03-13 20:39 UTC, Goldac77 commented on src/app.update.ts
> +          if(error.description === "Bad Request: IMAGE_PROCESS_FAILED"){
noted, I'll use error codes moving forward

2023-03-13 20:47 UTC, Goldac77 commented on src/rss/rss.service.ts
> +            let rssOption_title = await this.prisma.setting.findFirst({where: {feed_type: "title"}});
I'll correct that

2023-03-13 20:50 UTC, Goldac77 commented on src/rss/rss.service.ts
> +              gapItem.link
I missed that; it appeared after I tried merging changes from your repo to mine, I'll correct it

2023-03-13 20:52 UTC, Goldac77 commented on src/app.update.ts
> +        let message = `No valid image\n\n<a href="${lastItem.link}">${lastItem.title}</a>`;
intention was for the message sent to the chat if there's no valid image, I'll review it

2023-03-13 20:53 UTC, Goldac77 commented on src/app.update.ts
> +            let message = `No valid image\n\n<a href="${lastItem.link}">${lastItem.title}</a>`;
an oversight, I'll correct it also

2023-03-22 21:20 UTC, BoKKeR requested changes

2023-03-22 21:20 UTC, BoKKeR commented on src/telegram/telegram.processor.ts
> +          await this.telegramService.sendPhoto(
sendPhoto, sendTitle should be called instead from sendRss if possible

2023-03-22 21:20 UTC, BoKKeR commented on src/app.update.ts
> +let bot = new Telegraf(process.env.TOKEN);
could you check on this

2023-03-22 21:20 UTC, BoKKeR commented on src/telegram/telegram.processor.ts
> +    async function pauseQueue(error){
could you remove the commented out code

2023-03-22 21:20 UTC, BoKKeR commented on src/rss/rss.service.ts
> +
could you revert these changes

2023-03-22 21:20 UTC, BoKKeR commented on prisma/migrations/20230302193749_feed_type/migration.sql
> +-- RedefineTables
can you check on the merge conflicts

2023-03-22 21:20 UTC, BoKKeR commented on prisma/migrations/20230308110216_links_to_link/migration.sql
> +PRAGMA foreign_key_check;
I think it could be merged, either you can make the two changes the same time, or you can combine the two files since there is possibly only one line different.

2023-03-22 21:20 UTC, BoKKeR commented on prisma/migrations/20230308110216_links_to_link/migration.sql
> +PRAGMA foreign_key_check;
Could you add feed_type on feed also, and integrate it into the flow. 
- If feed_type in settings is set
- new link is added
- feed_type gets set on new link based on feed_type in settings

- If feed_type is not set
- initializes with a default

That would mean that you could check on the feed object instead how to send the link! And different feeds could be shown differently

2024-02-15 18:54 UTC, closed without merging